osx_image: xcode7.3
language: objective-c
script:
  - |
    xcodebuild build \
    -project azure-search-basics.xcodeproj \
    -scheme azure-search-basics \
    -sdk iphonesimulator \
    -destination 'platform=iOS Simulator,name=iPhone 6,OS=latest'
